### ISSUE TITLE
Upload other dataset process code for DDLearn

### ISSUE THREAD

**Issue by khan-yin** [microsoft/robustlearn#52]
Hello author, Recently I tried to implement the experiments in DDLearn. I noticed that DDLearn only provides the DSADS datasets process code in deal_dsads.py. Would you take the time to upload the other process code for PAMAP2 and USC-HAD?  It will save me a lot of time in making datasets from the complex structure in raw datasets 🥲.

**Comment by khan-yin** [comment]
Well, I have already processed the code for PAMAP2 and USC-HAD now🤣. From my understanding, we only need to modify the way the raw data is composed similar to DSADS, and the domain divide and augmentations can be shared.

There are 2 Q&As written by me:
Q: There may be a small question in USC-HAD, every activity in a single subject has 5 trials. Do we need to use all trials or just one trial? 

Q: Maybe I can make a PR for process code to help others when they implement the paper? 
The code for the two processes is below. You can review the code to see if there are any problems, and you can contact with me.
## PAMAP2
deal_PAMAP2.py
```python
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
import numpy as np
import os
import scipy.io as scio
import pandas as pd
# PAMAP2 sampling rate is 100Hz, the time window size is 5.12s, thus, a window consists of 512 readings
# merge data from a subject and sliding window, overlap=50%


def load_data(root_path, winsize, overlapsize):
    subject_num = 8
    act_num = 8 
    x_all, y_all, s_all = [], [], []
    IMU_hand = [f"IMU_hand_{i}" for i in range(1,18)]
    IMU_chest = [f"IMU_chest_{i}" for i in range(1,18)]
    IMU_ankle = [f"IMU_ankle_{i}" for i in range(1,18)]
    column_names = ['timestamp', 'activityID', 'heart rate']
    column_names.extend(IMU_hand)
    column_names.extend(IMU_chest)
    column_names.extend(IMU_ankle)
    need_name = ["IMU_hand_2","IMU_hand_3","IMU_hand_4",
                 "IMU_hand_8","IMU_hand_9","IMU_hand_10",
                "IMU_hand_11","IMU_hand_12","IMU_hand_13",
                "IMU_chest_2","IMU_chest_3","IMU_chest_4",
                "IMU_chest_8","IMU_chest_9","IMU_chest_10",
                "IMU_chest_11","IMU_chest_12","IMU_chest_13",
                "IMU_ankle_2","IMU_ankle_3","IMU_ankle_4",
                "IMU_ankle_8","IMU_ankle_9","IMU_ankle_10",
                "IMU_ankle_11","IMU_ankle_12","IMU_ankle_13"]
    # merge data/ a1-a8
    activitys = [1,2,3,4,12,13,16,17]
    for act in range(act_num):
        activity = activitys[act]
        # merge a/ p1-p8
        x_a, y_a, s_a = [], [], []
        for subnum in range(subject_num):
            subject = subnum+1
            sub_path = os.path.join(root_path, f'subject10{subject}.dat')
            raw_data = pd.read_csv(sub_path, sep=' ')
            raw_data.columns = column_names
            data = raw_data[raw_data['activityID'] == activity][need_name]
            has_nan = data.isna().any().any()
            if has_nan:
                # nan to mean
                print(f'nan in subject{subject} activity{activity}')
                data = data.fillna(data.mean())
            data_sub = np.zeros((1, 27))
            data_sub = np.vstack((data_sub, data))
            
            data_sub = data_sub[1:]
            x_s, y_s, s_s = getwin(
                data_sub, act, subnum, winsize, overlapsize)
            if subnum == 0:
                x_a, y_a, s_a = x_s, y_s, s_s
            else:
                x_a, y_a, s_a = np.vstack((x_a, x_s)), np.vstack(
                    (y_a, y_s)), np.vstack((s_a, s_s))
        if act == 0:
            x_all, y_all, s_all = x_a, y_a, s_a
        else:
            x_all, y_all, s_all = np.vstack((x_all, x_a)), np.vstack(
                (y_all, y_a)), np.vstack((s_all, s_a))
    return x_all, y_all, s_all


def getwin(x, y, s, winsize=512, overlapsize=256):
    l = len(x)
    stepsize = winsize-overlapsize
    h, t = 0, winsize
    xx, yy = [], []
    while t <= l:
        xx.append(x[h:t, :])
        yy.append(y)
        h += stepsize
        t += stepsize
    ss = np.ones(len(yy)) * s
    return np.array(xx), np.array(yy).reshape(-1, 1), np.array(ss).reshape(-1, 1)


if __name__ == '__main__':
    root_path = "../data/PAMAP/PAMAP2_Dataset/Protocol"
    save_path = '../process/PAMAP2/'
    winsize = 512
    overlapsize = 256
    x, y, s = load_data(root_path, winsize, overlapsize)
    if os.path.exists(save_path+'PAMAP2_processwin.npz'):
        pass
    else:
        np.savez(save_path+'PAMAP2_processwin.npz', x=x, y=y, s=s)
```

## USC-HAD
deal_USCHAD.py
```python
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
import numpy as np
import os
import scipy.io as scio
# USCHAD sampling rate is 100Hz, the time window size is 5s, thus, a window consists of 500 readings
# merge data from a subject and sliding window, overlap=50%


def load_data(root_path, winsize, overlapsize):
    subject_num = 14
    act_num = 12
    x_all, y_all, s_all = [], [], []
    # merge data/ a1-a12
    for act in range(act_num):
        activity = act+1
        # merge a/ p1-p14
        x_a, y_a, s_a = [], [], []
        for subnum in range(subject_num):
            subject = subnum+1
            sub_path = os.path.join(root_path, f'Subject{subject}/')
            data_sub = np.zeros((1, 6))
            t = 5 # do we need 5 trial?
            for i in range(1,t+1):
                file_path = os.path.join(sub_path, f'a{activity}t{i}.mat')
                amtn = scio.loadmat(file_path)
                print(amtn['sensor_readings'].shape)
                data_sub = np.vstack((data_sub, amtn['sensor_readings']))
            data_sub = data_sub[1:]
            x_s, y_s, s_s = getwin(
                data_sub, act, subnum, winsize, overlapsize)
            if subnum == 0:
                x_a, y_a, s_a = x_s, y_s, s_s
            else:
                x_a, y_a, s_a = np.vstack((x_a, x_s)), np.vstack(
                    (y_a, y_s)), np.vstack((s_a, s_s))
        if act == 0:
            x_all, y_all, s_all = x_a, y_a, s_a
        else:
            x_all, y_all, s_all = np.vstack((x_all, x_a)), np.vstack(
                (y_all, y_a)), np.vstack((s_all, s_a))
    return x_all, y_all, s_all



def getwin(x, y, s, winsize=500, overlapsize=250):
    l = len(x)
    stepsize = winsize-overlapsize
    h, t = 0, winsize
    xx, yy = [], []
    while t <= l:
        xx.append(x[h:t, :])
        yy.append(y)
        h += stepsize
        t += stepsize
    ss = np.ones(len(yy)) * s
    return np.array(xx), np.array(yy).reshape(-1, 1), np.array(ss).reshape(-1, 1)

if __name__ == '__main__':
    root_path = "../data/USC-HAD/USC-HAD"
    save_path = '../process/USC-HAD/'
    winsize = 500
    overlapsize = 250
    x, y, s = load_data(root_path, winsize, overlapsize)
    if os.path.exists(save_path+'USCHAD_processwin.npz'):
        pass
    else:
        np.savez(save_path+'USCHAD_processwin.npz', x=x, y=y, s=s)
```

**Comment by jindongwang** [comment]
@khan-yin Thanks for your contribution. The code seems fine to me. You can submit your PR after testing it.

**Comment by khan-yin** [comment]
Well, I tested the datasets in train20% and train100%, but the results were not well, especially in train20%. Except for DSADS(which has a small gap), the other two datasets have a larger gap😭. There are some reasons I guess you can help me.
## Possible reasons
- **The parameters settings.** I just keep the README command on DSADS, maybe it is not the best params for PAMAP2&USCHAD, I hope you could tell me the settings on these two datasets.
- **The domain split does not fit well.I think it is the critical reason.** I want to know how you split the data into domains. As the paper mentioned:
> We divide 8 subjects into 4 groups for DSADS and PAMAP2 and divide 14 subjects into 5 groups where each of group 0-3 consists of 3 subjects and the last consists of 2 subjects.

The code only provides the split method for DSADS. It just split by subject's order number, so I keep it the same way for other datasets, I am not sure if the 3 datasets keep the same splitting method in your experiments.
DSADS:
| domain-0   | domain-1   | domain-2   | domain-3   |
|------------|------------|------------|------------|
| subject1,2 | subject3,4 | subject5,6 | subject7,8 |

PAMAP2:
| domain-0   | domain-1   | domain-2   | domain-3   |
|------------|------------|------------|------------|
| subject1,2 | subject3,4 | subject5,6 | subject7,8 |

USCHAD:
| domain-0     | domain-1     | domain-2     | domain-3        | domain-4     |
|--------------|--------------|--------------|-----------------|--------------|
| subject1,2,3 | subject4,5,6 | subject7,8,9 | subject10,11,12 | subject13,14 |
- **seed affects the performance & training not stable.** I find that I run the **same settings in different seeds**, but I get test acc results **with a higher variance**, Maybe there's a way to make training more stable, or something wrong with my code, I'm not particularly experienced with this.

## Training results
Environment:
- 1*V100 32GB
- Python: 3.9.12
- PyTorch: 1.12.1
- Torchvision: 0.13.1
- CUDA: 10.2
- CUDNN: 7605
- NumPy: 1.21.5

### DSADS
![image](https://github.com/microsoft/robustlearn/assets/50772219/3bc66c02-1913-46d8-8c60-106e1007394b)

### PAMAP2
![image](https://github.com/microsoft/robustlearn/assets/50772219/ce45a743-2e1f-4cf2-b35a-f48f2f88492f)
### USCHAD
![image](https://github.com/microsoft/robustlearn/assets/50772219/0512d5d7-aeb6-48b1-963d-6a3a4f7e5498)

**Comment by jindongwang** [comment]
@khan-yin Thanks for the feedback! I'll let the first author have a look and then reply back to you.

**Comment by jindongwang** [comment]
@khan-yin The code for DDLearn is just updated. Please refer to the latest code to reproduce the results.

**Comment by qinxin-01** [comment]
@khan-yin We have upload the codes of data preprocess and other implement details of the other two datasets: PAMAP2 and USC-HAD. And update the requirements.
As for your concerns. There are many possible reasons. We analysis the possible reasons and answers are as follows:
1. We provide the script.sh when seed=1 for running to help get the best results. We run with seed=1,2,3 and the variances are shown in the paper.
2. The domain split may be a reason. The division of PAMAP2 and USC-HAD is as follows:

PAMAP2:

| domain-0     | domain-1      | domain-2      | domain-3      |
|--------------|---------------|--------------|--------------|
| subject 1,2  | subject 3,4   | subject 5,6   | subject 7,8   |

Activities are 1, 2, 3, 4, 12, 13, 16, 17, and we also deal with the NAN value. For more details, you can refer to the codes.

USC-HAD: 
We use all 5 trials. Since this dataset has a different amount of data for each subject, we divide it according to the following way to make domains more balance.

| domain-0        | domain-1        | domain-2       | domain-3        | domain-4       |
|-----------------|-----------------|----------------|-----------------|----------------|
| subject 1,3,10  | subject 2,5,13  | subject 4,7,9  | subject 6,8,14  | subject 11,12  |

3. The network framework and parameter of the other two datasets are different.

4. The difference between environments may cause some deviation, this is our environment:
3090 24GB
Python: 3.8.5
PyTorch: 1.7.1
Torchvision: 0.8.2
CUDA: 11.0
CUDNN: 8005
Numpy: 1.19.2


Results:

## Results

**DSADS 100% training data** 

| Source   | 1,2,3      | 0,2,3      | 0,1,3      | 0,1,2      | AVG        |
|----------|------------|------------|------------|------------|------------|
| Target   | 0          | 1          | 2          | 3          | -          |
| ERM      | 63.28      | 60.94      | 64.40      | 71.54      | 65.04      |
| Mixup    | 84.26      | 82.48      | 85.16      | 81.25      | 83.29      |
| Mldg     | 72.99      | 69.53      | 73.21      | 72.32      | 72.01      |
| RSC      | 65.40      | 80.25      | 76.79      | 75.11      | 74.39      |
| AND-Mask | 78.35      | 70.76      | 84.15      | 65.51      | 74.69      |
| SimCLR   | 72.54      | 75.65      | 77.08      | 73.83      | 74.78      |
| Fish     | 62.05      | 65.85      | 77.01      | 74.22      | 69.78      |
| DDLearn  | **93.81**  | **93.15**  | **92.49**  | **88.62**  | **92.02**  |

**DSADS 20% training data**

| Source   | 1,2,3      | 0,2,3      | 0,1,3      | 0,1,2      | AVG        |
|----------|------------|------------|------------|------------|------------|
| Target   | 0          | 1          | 2          | 3          | -          |
| ERM      | 56.92      | 68.30      | 58.93      | 73.88      | 64.51      |
| Mixup    | 75.22      | 71.32      | 70.20      | 70.98      | 71.93      |
| Mldg     | 59.60      | 69.20      | 68.08      | 69.42      | 66.58      |
| RSC      | 53.24      | 65.40      | 67.97      | 63.17      | 62.45      |
| AND-Mask | 58.59      | 63.06      | 70.09      | 62.05      | 63.45      |
| SimCLR   | 69.01      | 75.13      | 79.02      | 77.34      | 75.13      |
| Fish     | 53.01      | 62.95      | 69.75      | 66.52      | 63.06      |
| DDLearn  | **90.50**  | **90.28**  | **90.83**  | **84.53**  | **89.04**  |

**PAMAP2 100 training data**

| Source   | 1,2,3      | 0,2,3      | 0,1,3      | 0,1,2      | AVG        |
|----------|------------|------------|------------|------------|------------|
| Target   | 0          | 1          | 2          | 3          | -          |
| ERM      | 49.61      | 90.63      | 83.59      | 72.27      | 74.02      |
| Mixup    | 69.53      | 91.41      | 89.84      | 81.25      | 83.01      |
| Mldg     | 57.03      | 90.62      | 87.89      | 75.78      | 77.83      |
| RSC      | 52.34      | 89.84      | 87.89      | 80.47      | 77.64      |
| AND-Mask | 55.86      | 89.84      | 85.94      | 78.12      | 77.44      |
| SimCLR   | 62.89      | 83.59      | 80.86      | 74.61      | 75.49      |
| Fish     | 54.30      | 92.97      | 90.62      | 76.17      | 78.52      |
| DDLearn  | **81.02**  | **94.85**  | **88.34**  | **88.77**  | **88.25**  |

**PAMAP2 20 training data**

| Source   | 1,2,3      | 0,2,3      | 0,1,3      | 0,1,2      | AVG        |
|----------|------------|------------|------------|------------|------------|
| Target   | 0          | 1          | 2          | 3          | -          |
| ERM      | 47.66      | 74.61      | 78.91      | 78.13      | 69.82      |
| Mixup    | 57.03      | 76.17      | 82.03      | 76.56      | 72.95      |
| Mldg     | 52.34      | 78.52      | 78.52      | 75.39      | 71.19      |
| RSC      | 55.08      | 84.38      | 83.59      | 76.59      | 75.00      |
| AND-Mask | 51.56      | 85.16      | 83.59      | 75.00      | 73.83      |
| SimCLR   | 61.33      | 83.20      | 81.25      | 73.83      | 74.90      |
| Fish     | 48.83      | 87.11      | 84.38      | 73.05      | 73.34      |
| DDLearn  | **74.82**  | **87.13**  | **86.57**  | **82.97**  | **82.87**  |


**USC-HAD 100% training data**

| Source   | 1,2,3,4    | 0,2,3,4    | 0,1,3,4    | 0,1,2,4    | 0,1,2,3    | AVG        |
|----------|------------|------------|------------|------------|------------|------------|
| Target   | 0          | 1          | 2          | 3          | 4          |-           |
| ERM      | 83.07      | 74.74      | 79.17      | 53.39      | 64.58      | 70.99      |
| Mixup    | 84.11      | 81.25      | 86.20      | 72.66      | 75.00      | 79.84      |
| Mldg     | 79.17      | 71.09      | 77.08      | 65.62      | 60.68      | 70.73      |
| RSC      | 83.59      | 77.86      | 84.38      | 70.31      | 65.62      | 76.35      |
| AND-Mask | 82.29      | 76.56      | 80.73      | 63.02      | 69.53      | 74.43      |
| SimCLR   | 76.17      | 75.00      | 82.03      | 62.76      | 65.89      | 72.37      |
| Fish     | 83.85      | 77.08      | 86.72      | 65.36      | 74.22      | 77.45      |
| DDLearn  | **86.09**  | **83.33**  | **88.38**  | **79.23**  | **76.96**  | **82.80**  |

**USC-HAD 20% training data**

| Source   | 1,2,3,4    | 0,2,3,4    | 0,1,3,4    | 0,1,2,4    | 0,1,2,3    | AVG        |
|----------|------------|------------|------------|------------|------------|------------|
| Target   | 0          | 1          | 2          | 3          | 4          |-           |
| ERM      | 67.97      | 66.93      | 66.93      | 55.21      | 59.64      | 63.33      |
| Mixup    | 65.62      | 70.57      | 72.66      | 57.55      | 61.20      | 65.52      |
| Mldg     | 67.19      | 61.46      | 62.24      | 57.03      | 59.64      | 61.51      |
| RSC      | 74.22      | 72.14      | 75.52      | 58.33      | 64.58      | 68.96      |
| AND-Mask | 65.36      | 69.53      | 71.88      | 58.59      | 57.29      | 64.53      |
| SimCLR   | 67.97      | 68.36      | 78.13      | 59.90      | 61.72      | 67.21      |
| Fish     | 72.92      | 73.44      | 67.71      | 53.65      | 63.02      | 66.15      |
| DDLearn  | **77.22**  | **78.68**  | **80.56**  | **71.01**  | **78.23**  | **77.14**  |

**Comment by jindongwang** [comment]
@khan-yin Hi, are your problems solved?

**Comment by khan-yin** [comment]
Thank you for your very detailed response, It helps me a lot. However, I changed my environment the same as you and use the script.sh you provided, I still can not get results, lower than 5%-10% for each dataset, I don't know the reason. Maybe the only difference between us is the machine🥲 or have you ever changed the early stop pace in your code? Although I trained fully 500 epochs it is still not right. I want you to check the 2 points I did.
- I used links to download the three datasets: [DSADS](https://archive.ics.uci.edu/dataset/256/daily+and+sports+activities) [PAMAP2](https://archive.ics.uci.edu/dataset/231/pamap2+physical+activity+monitoring) [USCHAD](https://sipi.usc.edu/had/)
- the way I generated the dataset is to run `deal_dsads.py` first, then `data_preprocess_devide_domain.py`, and finally `raw_aug_loader.py`

if all these are right, I can't figure out the reason now.

Well, there is a small error when processing `deal_pamap.py`, the data columns you set are wrong I think. I think you might have missed the mistake.

```python
x_i = np.hstack((data_i[:, 4:7], data_i[:, 7:13], data_i[:, 21:24],
                         data_i[:, 27:33], data_i[:, 38:41], data_i[:, 44:50]))
```
you should change 7:13 to 10:16, the same distance in 21:24->27:33 and 38:41->44:50 as your paper mentioned.

```python
x_i = np.hstack((data_i[:, 4:7], data_i[:, 10:16], data_i[:, 21:24],
                         data_i[:, 27:33], data_i[:, 38:41], data_i[:, 44:50]))
```
Anyway, thank you very much!

**Comment by jindongwang** [comment]
@khan-yin Updated the code. Please check it again. I think you can directly email the first author and cc to me if you have further questions. This will be quick to help to solve your problems.

**Comment by qinxin-01** [comment]
@khan-yin 
1. The website seems have been updated for DSADS and PAMAP2, but the datasets seems the same.
2. The process to generate dataset is correct.
I reran the experiments with settings in the scripts.sh, and the results are consists with the tables above. This is a logs for the training print for the first task in script.sh. If you have any other questions, feel free to email me.
<img width="689" alt="image" src="https://github.com/microsoft/robustlearn/assets/47623422/a17cbb3a-9ebf-4ca2-b7af-3a097aa22a83">
