### ISSUE TITLE
about the reproduction of DIVERSIFY

### ISSUE THREAD

**Issue by gkyustc** [microsoft/robustlearn#57]
Thank you for your impressive work.

I noticed that your released code is built on Pytorch-1.13. However, the Cuda driver version on our server can not support Pytorch-1.13 and I can not install docker on our server. So, I created an environment with PyTorch-1.7.1 on our server and tried to reproduce the result. However, the result is very different from yours as shown in the image:
![image](https://github.com/microsoft/robustlearn/assets/20548130/f047e64a-ff17-4fdf-80d8-3aab5342ff4e)
So, I think there must be other things affecting the results. Could you provide more details about the environment with PyTorch-1.7.1 (for instance, the version of Scipy in our server is 1.7.3?
BTW, do you have any specific selection approach? 

Thank you for your help

Regards.

**Comment by gkyustc** [comment]
The test-env is 0

**Comment by jindongwang** [comment]
Hi @gkyustc, thank you for your interest in this work. First of all, different pytorch versions can definitely lead to different results, but I think the difference should not be large. Second, the best practice is to run hyperparameter search in different version due to such difference. Therefore, it is natural that you did not get the same or close results as we claimed in the code since you did not perform hyperparameter search in this 1.7 version. Am I right?
Suggestions for next steps: try to upgrade to the same version (you can leverage Google Colab which supports GPUs); run hyperparameter search on your current version to get the best results.
Involving @lw0517 here for further assistance.

**Comment by gkyustc** [comment]
Thank you for your reply. 

I recheck the hyperparameter and find that the epoch number in the paper is different from the cmd in readme.md. So I rerun the code and the result is shown in the following:
![image](https://github.com/microsoft/robustlearn/assets/20548130/967c5721-d518-4f58-975d-499eb501133e)
Here, I provide the command running the code:
**python train.py --data_dir ~/data/EMG/ --task cross_people --test_envs 0 --dataset emg --algorithm diversify --latent_domain_num 10 --alpha1 1.0 --alpha 1.0 --lam 0.0 --local_epoch 3 --max_epoch 150 --lr 0.01 --output ~/data/EMG/logs**

The above cmd is same as [the cmd in readme](https://github.com/microsoft/robustlearn/tree/main/diversify#how-to-run) excluding the --max_epoch. 

Please let me know if there is anything wrong. Thank you very much


Regards.

**Comment by jindongwang** [comment]
Hi, I don't think you carefully read my first reply. Since you use a different pytorch version, the environment is not the same. Therefore, you need to perform hyperparameter search instead of using the hyperparameters we provided.

**Comment by gkyustc** [comment]
Thank you for your advice.  I got a significant improvement on the performance after modifying the hyperparameter.  But there is still a little issue confusing me:
The results on the four test-envs are
0.6995      0.8616        0.7703         0.7667

It seems like the performance on the first two domains is not as stable as the last two domains. I am not sure if you have the same issue. Whatever, thank you for your help very much.

Regards.
